### ISSUE TITLE
build alias

### ISSUE THREAD

**Issue by jayvdb** [thombashi/python-package-template#1]
This part of setup.cfg causes all of your packages to fail to build using standard commands for RPM spec files.

```
[aliases]
build=sdist bdist_wheel
```

The normal command & resulting error is
```
[   49s] + /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
[   50s] usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
[   50s]    or: setup.py --help [cmd1 cmd2 ...]
[   50s]    or: setup.py --help-commands
[   50s]    or: setup.py cmd --help
[   50s] 
[   50s] error: invalid command 'bdist_wheel'
[   50s] error: Bad exit status from /var/tmp/rpm-tmp.UQO0zc (%build)
```

Also you are using `test_requires` to indicate your maintainer build requirements (tox, sphinx, etc), when it should be the minimum dependencies *needed* by the tests only.

I have a bunch of your packages at https://build.opensuse.org/project/show/home:jayvdb:py-new

and example of my workarounds at
https://build.opensuse.org/package/view_file/home:jayvdb:py-new/python-pathvalidate/python-pathvalidate.spec?expand=1

**Comment by jayvdb** [comment]
The alias for `sdist bdist_wheel` is often `release`, but that also usually includes the `upload` command.

There is now a `releasecmd` plugin which streamlines the process a bit.

**Comment by thombashi** [comment]
Thank you for your feedback and workarounds. 

I had applied the following changes to most of my packages:

- remove the `build` alias 
- reduce dependencies described in `test_requires`

Does this solve your problem?

**Comment by jayvdb** [comment]
Looks good. thx.
